BOOLEANS:
  TABLIST: true
  SCOREBOARD: true
PLAYER-JOIN-MESSAGE: "%player% has joined the server"
SET-SLOTS: 80
CHAT-FORMAT:
  ENABLE: true
  FORMAT: "%player_name% &8» %message%"
FILE-RELOAD: "&AConfig Reloaded"
TABLIST:
  HEADER: "its a header"
  FOOTER: "its a footer"
JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""

RULES-COMMAND:
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""