BOOLEANS:
  TABLIST: true
  SCOREBOARD: true
PLAYER-JOIN-MESSAGE: "%player% has joined the server"

CHAT-FORMAT:
  ENABLE: true
  FORMAT: "%player_name% &8» %message%"

FILE-RELOAD: "&AConfig Reloaded"

JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""