FILE-RELOAD: "&aConfig Reloaded"
JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - "&6Bienvenido &f%player_name% &6a &fSurvival 1.17"

BOOLEANS:
  BROADCAST-QUIT: false
  BROADCAST-JON: false

BROADCAST:
  JOIN: "<player> has joined"
  QUIT: "<player> has left"

CHAT:
  ENABLED: true
  FORMAT: "%player% &8» &r%message%"

CAMA-COORDS-COMMAND:
    - "&fCoordenadas de tu Cama&7: "
    - " &8» &aMundo - <bed-world>"
    - " &8» &aX - <bed-x-coord>"
    - " &8» &aY - <bed-y-coord>"
    - " &8» &aZ - <bed-z-coord>"

COORDS:
  YOUR-COORDS:
    - "&fTus Coordenadas&7: "
    - " &8» &aMundo - <world>"
    - " &8» &aX - <x-coord>"
    - " &8» &aY - <y-coord>"
    - " &8» &aZ - <z-coord>"
  OTHER-PLAYER-COORDS:
    - "&fCoordenadas de <target_player>&7:"
    - " &8» &aMundo - <target-world>"
    - " &8» &aX - <x-target-player>"
    - " &8» &aY - <y-target-player>"
    - " &8» &aZ - <z-target-player>"
  PLAYER-NOT-FOUND: "&cJugador <target_player> no esta en linea actualmente"
  PLAYER-NO-EXIST: "&CJugador <target_player> no existe"

MORE-COMMAND: "&aThe item you have been holding has been stacked to 64"
MORE-COMMAND-AMOUNT: "&aThe item you have been holding has been stacked to <amount>"
BED-INSTANT-SLEEP: false

FLY-COMMAND:
  ENABLED: "&8* &aTu modo de vuelo a sido activado."
  DISABLED: "&8* &cTu modo de vuelo a sido desactivado."

ENTITIES:
  POPPY-DROP: false
  GUNPOWDER-BOOST: true
  GHAST-THEAR-BOOST: true