FILE-RELOAD: "&aConfig Reloaded"
JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - "&7&m---------------------------"
    - "&6Bienvenido &f%player_name% &6a JazePvP &fSurvival 1.16"
    - ""
    - "&6Discord&7: &fhttps://discord.gg/a9juZ6EzR8"
    - "&7&m---------------------------"

BROADCAST:
  JOIN: "%player% has joined"
  QUIT: "%player% has left"

CHAT:
  ENABLED: true
  FORMAT: "%player% &8» &r%message%"

CAMA-COORDS-COMMAND:
  - "&fCoordenadas de tu Cama&7: "
  - " &8» &aX - %player_bed_x%"
  - " &8» &aY - %player_bed_y%"
  - " &8» &aZ - %player_bed_z%"

COORDS:
  NO-ARGS-COMMAND:
    - "&fTus Coordenadas&7: "
    - " &8» &aX - %player_x%"
    - " &8» &aY - %player_y%"
    - " &8» &aZ - %player_z%"
  OTHER-PLAYER-COORDS:
    - "&fCoordenadas de %target_player%&7:"
    - " &8» &aX - %otherplayer_locx_%target_player%%"
    - " &8» &aY - %otherplayer_locy_%target_player%%"
    - " &8» &aZ - %otherplayer_locz_%target_player%%"
  PLAYER-NOT-FOUND: "&cJugador %target_player% no esta en linea actualmente"
  PLAYER-NO-EXIST: "&CJugador %target_player% no existe"

MORE-COMMAND: "&aThe item you have been holding has been stacked to 64"