JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - "&6Bienvenido &f<player> &6a &fSurvival 1.17"

CHAT:
  ENABLED: true
  FORMAT: "<rank-prefix>%player% &8» &r%message%"

ENTITIES:
  POPPY-DROP: false
  GUNPOWDER-BOOST: true
  GHAST-THEAR-BOOST: true
  BEE-BOOST: true
  CAT-BOOST: true