JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - "&7&m----------------------------------------------------"
    - "&6Bienvenido &f<player> &6a &fSurvival 1.18.1"
    - ""
    - "&eSe te recomienda como jugador novato mirar el comando /help"
    - "&epara enterarte de lo que puedes llegar a hacer"
    - ""
    - "&eTambien se te recomienda que entres a nuestro discord"
    - "&epara que puedas ver los crafteos que hay creados"
    - ""
    - "&eEn el canal survival-crafteos puedes verlos todos"
    - ""
    - "&ahttps://discord.gg/zDn7yN2j9T"
    - "&7&m----------------------------------------------------"

BOOLEANS:
  TAB: true
  SCOREBOARD: true
  CHAT: true

SEAL-KICK: true

ENTITIES:
  POPPY-DROP: false
  GUNPOWDER-BOOST: true
  GHAST-THEAR-BOOST: true
  BEE-BOOST: true
  CAT-BOOST: true