FILE-RELOAD: "&aConfig Reloaded"
JOIN-MESSAGE:
  ENABLE: true
  LINES:
    - "&6Bienvenido &f%player_name% &6a &fSurvival 1.17"

BOOLEANS:
  BROADCAST-QUIT: false
  BROADCAST-JON: false

BROADCAST:
  JOIN: "<player> has joined"
  QUIT: "<player> has left"

CHAT:
  ENABLED: true
  FORMAT: "<rank-prefix>%player% &8» &r%message%"

ENTITIES:
  POPPY-DROP: false
  GUNPOWDER-BOOST: true
  GHAST-THEAR-BOOST: true
  BEE-BOOST: true
  CAT-BOOST: true